var DEMO_SHIPMENTS = {
  '1': [
    {
      id:101, entry:'EL-2025-004821', bl:'MSCUSVLA234567',
      vessel:'MSC ELENA', container:'MSCU7284013',
      product:'Camarones congelados IQF — 2,400 kg',
      origin:'Puerto Acajutla, SV', dest:'Port of Los Angeles, CA',
      etd:'28 Mar 2025', eta:'14 Abr 2025', arrived:'15 Abr 2025',
      status:'held', broker:'Global Customs Brokers LLC',
      fda_holds:[
        { code:'INSANITARY', section:'402(a)(4), 801(a)(3)', desc:'Producto preparado bajo condiciones insanitarias.' },
        { code:'LISTERIA',   section:'402(a)(1), 801(a)(3)', desc:'Se detecto Listeria monocytogenes.' },
      ],
      costs_normal:[['Flete maritimo',4100],['Seguro',480],['Arancel (7.5%)',1350],['Broker aduanal',920],['ISF Filing',85]],
      costs_extra: [['Almacenaje refrigerado (12 dias)',1680],['Analisis laboratorio FDA',750],['Asesoria legal',1200]],
      timeline:[
        {lbl:'Embarcado',   date:'28 Mar', sub:'Acajutla SV',    st:'done'},
        {lbl:'En transito', date:'28 Mar-15 Abr', sub:'MSC ELENA', st:'done'},
        {lbl:'Prior Notice',date:'14 Abr', sub:'FDA PNSI',       st:'done'},
        {lbl:'Arribo',      date:'15 Abr', sub:'Los Angeles',    st:'done'},
        {lbl:'CBP',         date:'15 Abr', sub:'ACE Portal',     st:'done'},
        {lbl:'FDA Detencion',date:'16 Abr',sub:'OASIS/PREDICT',  st:'blocked'},
        {lbl:'Liberacion',  date:'Pendiente', sub:'—',           st:'pending'},
      ],
      agencies:[
        {name:'CBP Aduanas',status:'pass',note:'Documentacion completa. Entry Summary aceptada.'},
        {name:'USDA APHIS', status:'na',  note:'No aplica para mariscos congelados de El Salvador.'},
        {name:'FDA',        status:'fail',note:'OASIS emitio detencion. Import Alert 16-81. 90 dias para responder.'},
      ],
    },
    {
      id:102, entry:'EL-2025-003910', bl:'MSCUSVLA198432',
      vessel:'MSC MARIA', container:'MSCU6192847',
      product:'Camarones crudos — 1,800 kg',
      origin:'Puerto Acajutla, SV', dest:'Port of Miami, FL',
      etd:'10 Feb 2025', eta:'28 Feb 2025', arrived:'27 Feb 2025',
      status:'clear', broker:'Global Customs Brokers LLC',
      fda_holds:[],
      costs_normal:[['Flete maritimo',3800],['Seguro',420],['Arancel (7.5%)',1200],['Broker aduanal',920]],
      costs_extra: [],
      timeline:[
        {lbl:'Embarcado',   date:'10 Feb', sub:'Acajutla SV',  st:'done'},
        {lbl:'En transito', date:'10-27 Feb', sub:'MSC MARIA', st:'done'},
        {lbl:'Prior Notice',date:'26 Feb', sub:'FDA PNSI',     st:'done'},
        {lbl:'Arribo',      date:'27 Feb', sub:'Miami FL',     st:'done'},
        {lbl:'CBP',         date:'27 Feb', sub:'Released',     st:'done'},
        {lbl:'FDA',         date:'28 Feb', sub:'May Proceed',  st:'done'},
        {lbl:'Liberado',    date:'28 Feb', sub:'Entregado',    st:'done'},
      ],
      agencies:[
        {name:'CBP Aduanas',status:'pass',note:'Arancel pagado. Entry Summary aprobada.'},
        {name:'USDA APHIS', status:'na',  note:'No aplica.'},
        {name:'FDA',        status:'pass',note:'OASIS: "May Proceed" automatico en 22 minutos.'},
      ],
    },
  ],
  '2': [
    {
      id:103, entry:'EL-2025-004756', bl:'EVERGOLDSV22345',
      vessel:'EVER GOLDEN', container:'EGHU9341022',
      product:'Cafe verde en grano — 5,000 kg',
      origin:'Puerto Acajutla, SV', dest:'Port of Miami, FL',
      etd:'10 Mar 2025', eta:'28 Mar 2025', arrived:'27 Mar 2025',
      status:'clear', broker:'Ameritrade Customs Corp.',
      fda_holds:[],
      costs_normal:[['Flete maritimo',2900],['Seguro',310],['Arancel (0% CAFTA-DR)',0],['Broker aduanal',780],['Almacenaje (2 dias)',280]],
      costs_extra: [],
      timeline:[
        {lbl:'Embarcado',   date:'10 Mar', sub:'Acajutla SV',    st:'done'},
        {lbl:'En transito', date:'10-27 Mar', sub:'EVER GOLDEN', st:'done'},
        {lbl:'Prior Notice',date:'26 Mar', sub:'FDA PNSI',       st:'done'},
        {lbl:'Arribo',      date:'27 Mar', sub:'Miami FL',       st:'done'},
        {lbl:'CBP',         date:'27 Mar', sub:'Released',       st:'done'},
        {lbl:'FDA',         date:'28 Mar', sub:'May Proceed',    st:'done'},
        {lbl:'Liberado',    date:'29 Mar', sub:'Entregado',      st:'done'},
      ],
      agencies:[
        {name:'CBP Aduanas',status:'pass',note:'CAFTA-DR aplicado. 0% arancel para cafe de El Salvador.'},
        {name:'USDA APHIS', status:'pass',note:'Phytosanitary Certificate valido de SENASA El Salvador.'},
        {name:'FDA',        status:'pass',note:'OASIS: "May Proceed" automatico. Sin restricciones.'},
      ],
    },
  ],
  '3': [
    {
      id:104, entry:'EL-2025-004910', bl:'COSCHOUSV45678',
      vessel:'COSCO HARMONY', container:'CSNU4521789',
      product:'Telas algodon organico — 8,200 kg',
      origin:'Puerto Cortes, HN', dest:'Port of Houston, TX',
      etd:'02 Abr 2025', eta:'22 Abr 2025', arrived:'En ruta',
      status:'transit', broker:'Texas Customs Services LLC',
      fda_holds:[],
      costs_normal:[['Flete maritimo',4200],['Seguro',490],['Arancel (12%)',2460],['Broker aduanal',920]],
      costs_extra: [],
      timeline:[
        {lbl:'Embarcado',   date:'02 Abr', sub:'Pto. Cortes HN',  st:'done'},
        {lbl:'En transito', date:'En curso', sub:'COSCO HARMONY', st:'active'},
        {lbl:'Prior Notice',date:'N/A',   sub:'No aplica',        st:'pending'},
        {lbl:'Arribo',      date:'22 Abr est.', sub:'Houston TX', st:'pending'},
        {lbl:'CBP',         date:'Pendiente', sub:'—',            st:'pending'},
        {lbl:'FDA',         date:'N/A',   sub:'No aplica',        st:'pending'},
        {lbl:'Liberacion',  date:'Est. 24 Abr', sub:'—',          st:'pending'},
      ],
      agencies:[
        {name:'CBP Aduanas',status:'pending',note:'ISF presentado. Entry Summary al arribar.'},
        {name:'USDA APHIS', status:'na',     note:'No aplica para fibras textiles.'},
        {name:'FDA',        status:'na',     note:'No aplica — producto textil no regulado por FDA.'},
      ],
    },
  ],
  '4': [
    {
      id:105, entry:'EL-2025-004888', bl:'HAPAGNYSV33201',
      vessel:'HAPAG EXPRESS', container:'HLCU3312045',
      product:'Suplementos dieteticos — 450 kg',
      origin:'Puerto Acajutla, SV', dest:'Port of New York, NJ',
      etd:'18 Mar 2025', eta:'06 Abr 2025', arrived:'07 Abr 2025',
      status:'review', broker:'Northeast Import Associates',
      fda_holds:[],
      costs_normal:[['Flete maritimo',3100],['Seguro',280],['Arancel (5%)',890],['Broker aduanal',780]],
      costs_extra: [],
      timeline:[
        {lbl:'Embarcado',   date:'18 Mar', sub:'Acajutla SV',     st:'done'},
        {lbl:'En transito', date:'18 Mar-7 Abr', sub:'HAPAG',    st:'done'},
        {lbl:'Prior Notice',date:'05 Abr', sub:'FDA PNSI',        st:'done'},
        {lbl:'Arribo',      date:'07 Abr', sub:'New York NJ',     st:'done'},
        {lbl:'CBP',         date:'En curso', sub:'Under Review',  st:'active'},
        {lbl:'FDA PREDICT', date:'Evaluando', sub:'Score pendiente', st:'active'},
        {lbl:'Liberacion',  date:'Pendiente', sub:'—',            st:'pending'},
      ],
      agencies:[
        {name:'CBP Aduanas',status:'pending',note:'Revision de valor declarado y clasificacion HTS 2106.90.'},
        {name:'USDA APHIS', status:'na',     note:'No aplica para suplementos procesados.'},
        {name:'FDA',        status:'pending',note:'PREDICT evaluando riesgo. Suplementos requieren registro FSMA.'},
      ],
    },
  ],
  '5': [], // admin ve todos
};

var DEMO_REFUSALS = [
  { id:'EL-2024-001201', firm:'Alimentos Del Mar S.A.', city:'San Salvador', cat:'Human Foods', product:'Shrimp, Frozen', charges:'INSANITARY, LISTERIA', date:'2024-11-15' },
  { id:'EL-2024-000987', firm:'Exportadora San Miguel', city:'San Miguel',   cat:'Human Foods', product:'Vegetables, Fresh', charges:'PESTICIDE', date:'2024-10-28' },
  { id:'EL-2024-000845', firm:'Bocadillos SV Ltda.',    city:'Santa Ana',    cat:'Human Foods', product:'Snack Foods', charges:'NO ENGLISH, LIST INGRE', date:'2024-09-14' },
  { id:'EL-2024-000712', firm:'Suplementos Naturales',  city:'San Salvador', cat:'Drugs',       product:'Dietary Supplement', charges:'UNAPPROVED, DRUG GMPS', date:'2024-08-30' },
  { id:'EL-2024-000634', firm:'Bebidas Tropicales SV',  city:'Soyapango',   cat:'Human Foods', product:'Juice, Fruit', charges:'UNSAFE ADD, NUTRIT LBL', date:'2024-08-10' },
  { id:'EL-2024-000521', firm:'Conservas del Pacifico', city:'La Libertad',  cat:'Human Foods', product:'Seafood, Canned', charges:'INSANITARY, FILTHY', date:'2024-07-22' },
  { id:'EL-2024-000448', firm:'Cosmeticos Bella SV',    city:'San Salvador', cat:'Cosmetics',   product:'Skin Care', charges:'CSTIC LBLG, NO ENGLISH', date:'2024-06-30' },
  { id:'EL-2024-000390', firm:'Granos y Cereales SV',   city:'Usulutan',     cat:'Human Foods', product:'Grain Products', charges:'AFLATOXIN', date:'2024-06-05' },
  { id:'EL-2024-000312', firm:'Mariscos Pacifico SV',   city:'La Union',     cat:'Human Foods', product:'Fish, Dried', charges:'INSANITARY, OFF ODOR', date:'2024-05-18' },
  { id:'EL-2024-000278', firm:'Lacteos del Sur SV',     city:'San Vicente',  cat:'Human Foods', product:'Cheese, Soft', charges:'LISTERIA, BACTERIA', date:'2024-04-29' },
  { id:'EL-2024-000201', firm:'Farmacia Natural SV',    city:'San Salvador', cat:'Drugs',       product:'Herbal Supplement', charges:'LACKS FIRM, NUTRIT LBL', date:'2024-04-10' },
  { id:'EL-2024-000145', firm:'Dulces y Confites SV',   city:'Sonsonate',    cat:'Human Foods', product:'Candy, Sugar', charges:'COLOR LBLG, UNSAFE ADD', date:'2024-03-22' },
];

var DEMO_ALERTS = [
  { num:'12-10',  date:'12/23/2025', title:'Detention Without Physical Examination of Cheese Due to Microbiological Contamination', products:'Queso, Productos lacteos', reason:'Contaminacion microbiologica en queso', charge:'402(a)(1)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_9.html' },
  { num:'16-120', date:'03/19/2026', title:'Detention Without Physical Examination of Fish and Fishery Products from Foreign Processors Not in Compliance with Seafood HACCP Regulation', products:'Pescado, Productos pesqueros procesados', reason:'Incumplimiento de regulacion HACCP de mariscos (21 CFR Part 123)', charge:'402(a)(4)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_25.html' },
  { num:'16-74',  date:'02/13/2026', title:'Detention Without Physical Examination of Uneviscerated Fish or Partially Eviscerated Fish that are Salt-Cured, Dried, Smoked, Pickled, Fermented or Brined', products:'Pescado seco, ahumado, en salmuera o fermentado', reason:'Condiciones insanitarias en procesamiento de pescado curado o ahumado', charge:'402(a)(4)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_48.html' },
  { num:'16-81',  date:'03/18/2026', title:'Detention Without Physical Examination of Seafood Products Due to the Presence of Salmonella', products:'Mariscos, Camarones, Pescados y productos del mar', reason:'Presencia de Salmonella — adulteracion bajo 402(a)(1)', charge:'402(a)(1)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_49.html' },
  { num:'23-14',  date:'03/13/2026', title:'Detention Without Physical Examination of Food Products Due to the Presence of Mycotoxins', products:'Mani, maiz, nueces, cereales, granos y derivados', reason:'Presencia de micotoxinas (aflatoxinas, deoxinivalenol, fumonisinas, ocratoxina A)', charge:'402(a)(1)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_581.html' },
  { num:'45-02',  date:'03/18/2026', title:'Detention Without Physical Examination and Guidance of Foods Containing Illegal and/or Undeclared Colors', products:'Alimentos con colorantes ilegales o no declarados', reason:'Colorantes no aprobados o no declarados en etiqueta', charge:'402(c), 403(k)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_118.html' },
  { num:'66-41',  date:'03/17/2026', title:'Detention Without Physical Examination of Unapproved New Drugs Promoted in the U.S.', products:'Medicamentos nuevos sin aprobacion FDA', reason:'Medicamento nuevo sin NDA aprobada — 505(a)', charge:'505(a)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_190.html' },
  { num:'99-05',  date:'03/18/2026', title:'Detention Without Physical Examination of Raw Agricultural Products for Pesticides', products:'Frutas, vegetales, granos crudos', reason:'Residuos de pesticidas en productos agricolas crudos', charge:'402(a)(2)(B)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_258.html' },
  { num:'99-08',  date:'03/20/2026', title:'Detention without Physical Examination of Processed Human and Animal Foods for Pesticides', products:'Alimentos procesados para humanos y animales', reason:'Residuos de pesticidas en alimentos procesados', charge:'402(a)(2)(B)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_259.html' },
  { num:'99-19',  date:'03/13/2026', title:'Detention Without Physical Examination of Food Products Due to the Presence of Salmonella', products:'Alimentos para consumo humano, diversas categorias', reason:'Presencia de Salmonella en alimentos', charge:'402(a)(1)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_263.html' },
  { num:'99-21',  date:'01/30/2026', title:'Detention Without Physical Examination of Food Products Containing Undeclared Added Sulfiting Agents', products:'Alimentos con sulfitos no declarados', reason:'Sulfitos no declarados en etiqueta', charge:'403(k)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_265.html' },
  { num:'99-39',  date:'03/18/2026', title:'Detention Without Physical Examination of Imported Food Products That Appear to Be Misbranded', products:'Productos con etiquetado incorrecto o enganoso', reason:'Misbranding — etiquetado falso o incompleto', charge:'403(a)(1)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_1144.html' },
  { num:'99-42',  date:'03/17/2026', title:'Detention Without Physical Examination of Foods Due to Heavy Metal (Toxic Element) Contamination', products:'Alimentos con contaminacion de plomo, arsenico, cadmio, mercurio', reason:'Contaminacion por metales pesados — sustancias venenosas', charge:'402(a)(1)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_1167.html' },
  { num:'99-43',  date:'03/05/2026', title:'Detention Without Physical Examination of Ready-To-Eat Human Food Products That Appear to Have Been Prepared Under Insanitary Conditions', products:'Alimentos listos para comer (RTE)', reason:'Condiciones insanitarias en preparacion de alimentos RTE', charge:'402(a)(4)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_1168.html' },
  { num:'99-45',  date:'03/11/2026', title:'Detention Without Physical Examination of Food Products That Are or Contain an Unsafe Food Additive', products:'Alimentos con aditivos no aprobados por FDA', reason:'Aditivo alimentario inseguro — 402(a)(2)(C)', charge:'402(a)(2)(C)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_1173.html' },
  { num:'99-47',  date:'02/12/2026', title:'Detention Without Physical Examination of Human Food Products That Appear to be Adulterated for Economic Gain', products:'Alimentos adulterados por ganancia economica', reason:'Adulteracion economica — sustitucion de ingredientes, fraude', charge:'402(b)', url:'https://www.accessdata.fda.gov/cms_ia/importalert_1178.html' },
];

var DEMO_CHARGES = [
  { code:'INSANITARY', section:'402(a)(4), 801(a)(3)', cat:'ADULTERATION', es:'Preparado bajo condiciones insanitarias, pudo contaminarse o ser perjudicial para la salud', en:'Prepared under insanitary conditions whereby it may have been contaminated.' },
  { code:'LISTERIA',   section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene Listeria monocytogenes, sustancia venenosa perjudicial para la salud', en:'Contains Listeria monocytogenes, a poisonous and deleterious substance.' },
  { code:'SALMONELLA', section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene Salmonella, sustancia venenosa que puede ser perjudicial para la salud', en:'Contains Salmonella, a poisonous and deleterious substance.' },
  { code:'PESTICIDE',  section:'402(a)(2)(B), 801(a)(3)', cat:'ADULTERATION', es:'Contiene residuos de quimico plaguicida que adulteran el articulo', en:'Contains a pesticide chemical residue causing adulteration.' },
  { code:'AFLATOXIN',  section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene micotoxina (aflatoxina), sustancia venenosa perjudicial para la salud', en:'Contains a mycotoxin, a poisonous and deleterious substance.' },
  { code:'FILTHY',     section:'402(a)(3), 801(a)(3)', cat:'ADULTERATION', es:'Consiste en todo o en parte de sustancia sucia, putrida o descompuesta', en:'Consists of filthy, putrid, or decomposed substance.' },
  { code:'UNSAFE ADD', section:'402(a)(2)(C)(i), 801(a)(3)', cat:'ADULTERATION', es:'Contiene un aditivo alimentario inseguro segun la seccion 409', en:'Bears or contains an unsafe food additive within section 409.' },
  { code:'DRUG GMPS',  section:'501(a)(2)(B), 801(a)(3)', cat:'ADULTERATION', es:'Metodos de fabricacion no cumplen con las BPM vigentes de medicamentos', en:'Methods used in manufacture do not conform to current GMP.' },
  { code:'NO ENGLISH', section:'403(f), 801(a)(3)',    cat:'MISBRANDING',  es:'Informacion requerida no esta en ingles en la etiqueta (21 CFR 101.15)', en:'Required information not prominently placed in English per 21 CFR 101.15.' },
  { code:'LIST INGRE', section:'403(i)(2), 801(a)(3)', cat:'MISBRANDING',  es:'Etiqueta no lleva el nombre comun o usual de cada ingrediente', en:'Label fails to bear the common or usual name of each ingredient.' },
  { code:'NUTRIT LBL', section:'403(q), 801(a)(3)',    cat:'MISBRANDING',  es:'Etiqueta no presenta la informacion nutricional requerida (Nutrition Facts)', en:'Label fails to bear the required nutrition information.' },
  { code:'ALLERGEN',   section:'403(w), 801(a)(3)',    cat:'MISBRANDING',  es:'Etiqueta no declara todos los alergenos alimentarios mayores presentes', en:'Label fails to declare all major food allergens per section 403(w)(1).' },
  { code:'LACKS FIRM', section:'403(e)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Empaque sin nombre y lugar de negocio del fabricante, empacador o distribuidor', en:'Label fails to bear the name and place of business of the manufacturer.' },
  { code:'UNAPPROVED', section:'505(a), 801(a)(3)',    cat:'MISBRANDING',  es:'Nuevo medicamento sin Solicitud de Nuevo Medicamento (NDA) aprobada por FDA', en:'New drug without an approved New Drug Application (NDA).' },
  { code:'FALSE',      section:'403(a)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Rotulado es falso o enganoso en cualquier particular', en:'Labeling is false or misleading in any particular.' },
  { code:'COLOR LBLG', section:'403(k), 801(a)(3)',    cat:'MISBRANDING',  es:'Contiene colorante artificial y no tiene etiquetado que declare ese hecho', en:'Contains artificial coloring and fails to bear labeling stating that fact.' },
  { code:'BACTERIA',   section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene sustancia venenosa y deleterea que puede hacerlo perjudicial', en:'Contains a poisonous and deleterious substance which may render it injurious.' },
  { code:'TRANSFAT',   section:'403(q), 801(a)(3)',    cat:'MISBRANDING',  es:'Etiqueta nutricional no proporciona la cantidad de grasas trans', en:'Nutrition label does not provide the amount of trans fat.' },
  { code:'ALLERGEN',   section:'403(w), 801(a)(3)',    cat:'MISBRANDING',  es:'No declara todos los alergenos mayores presentes en el producto', en:'Label fails to declare all major food allergens present in the product.' },
  { code:'MELAMINE',   section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene melamina o analogo, aditivo inseguro segun la Seccion 409', en:'Contains melamine and/or a melamine analog, unsafe food additive.' },
  { code:'EXPIRED',    section:'501(c), 801(a)(3)',    cat:'ADULTERATION', es:'Calidad esta por debajo de lo declarado — producto pasado su fecha de vencimiento', en:'Quality falls below that which it purports — past labeled expiration date.' },
  { code:'E COLI 157', section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene E. coli O157:H7 (EHEC), sustancia venenosa perjudicial para la salud', en:'Contains E. coli O157:H7 (EHEC), a poisonous and deleterious substance.' },
  { code:'VIBRIO',     section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene Vibrio cholerae, sustancia venenosa y deleterea', en:'Contains Vibrio cholerae, a poisonous and deleterious substance.' },
  { code:'SHIGELLA',   section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene Shigella, sustancia venenosa que puede hacerlo perjudicial', en:'Contains Shigella, a poisonous and deleterious substance.' },
  { code:'HISTAMINE',  section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene histamina en cantidad que ordinariamente lo hace perjudicial para la salud', en:'Contains histamine in such quantity as ordinarily renders it injurious to health.' },
  { code:'DIOXIN',     section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene dioxinas o compuestos PCB, sustancias venenosas o aditivos no aprobados', en:'Contains dioxins and/or PCB compounds, poisonous substances.' },
  { code:'PATULIN',    section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene Patulina, sustancia venenosa que puede hacerlo perjudicial para la salud', en:'Contains Patulin, a poisonous and deleterious substance.' },
  { code:'FSVP VIO',   section:'805, 801(a)(3)',        cat:'MISBRANDING',  es:'Importador en violacion de la seccion 805 — Programa de Verificacion de Proveedores', en:'Importer is in violation of section 805 — Foreign Supplier Verification Program.' },
  { code:'SUPPL GMP',  section:'402(g)(1), 801(a)(3)', cat:'ADULTERATION', es:'Suplemento dietetico preparado bajo condiciones que no cumplen las BPM actuales', en:'Dietary supplement prepared under conditions not meeting current GMP regulations.' },
  { code:'CHOKE HZRD', section:'402(a)(3), 801(a)(3)', cat:'ADULTERATION', es:'No apto para consumo — contiene objeto extrano que puede representar peligro de asfixia', en:'Contains a foreign object which may pose a choking hazard.' },
  { code:'COUMARIN',   section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene Cumarina, sustancia venenosa que puede hacerlo perjudicial para la salud', en:'Contains Coumarin, a poisonous or deleterious substance.' },
  { code:'CYCLAMATE',  section:'402(a)(2)(C), 801(a)(3)', cat:'ADULTERATION', es:'Contiene ciclamato, aditivo alimentario inseguro segun la Seccion 409', en:'Contains cyclamate, an unsafe food additive within Section 409.' },
  { code:'SACCHARIN',  section:'403(o), 801(a)(3)',    cat:'MISBRANDING',  es:'Contiene Sacarina y su etiqueta no lleva la declaracion de advertencia requerida', en:'Contains Saccharin and label fails to bear the required warning statement.' },
  { code:'OFF ODOR',   section:'402(a)(3), 801(a)(3)', cat:'ADULTERATION', es:'Producto sucio, putrido o descompuesto. Contiene mal olor', en:'Consists of filthy, putrid, or decomposed substance. Contains an off odor.' },
  { code:'POISONOUS',  section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene una sustancia venenosa o deleterea que puede hacerlo perjudicial', en:'Bears or contains a poisonous or deleterious substance.' },
  { code:'STD IDENT',  section:'403(g)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Se presenta como alimento con estandar de identidad pero no cumple con dicha definicion', en:'Purports to be a food with a standard of identity but does not conform.' },
  { code:'USUAL NAME', section:'403(i)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Etiqueta no lleva el nombre comun o usual del alimento', en:'Label fails to bear the common or usual name of the food.' },
  { code:'HEALTH C',   section:'403(r)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Etiqueta lleva declaracion de contenido nutricional o de salud no autorizada por FDA', en:'Label bears an unauthorized nutrient content or health claim.' },
  { code:'DIETARYING', section:'403(s)(2)(A), 801(a)(3)', cat:'MISBRANDING', es:'Etiqueta del suplemento no lista nombre y cantidad de cada ingrediente dietetico', en:'Dietary supplement label fails to list the name and quantity of each dietary ingredient.' },
  { code:'RX LEGEND',  section:'502(f)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Medicamento de prescripcion sin leyenda requerida — "Rx Only"', en:'Prescription drug without a prescription drug legend as required.' },
  { code:'POIS CHLOR', section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene cloranfenicol, sustancia venenosa que puede hacerlo perjudicial', en:'Contains chloramphenicol, a poisonous or deleterious substance.' },
  { code:'MYCOTOXIN',  section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene micotoxina (aflatoxina, DON, fumonisina u ocratoxina A)', en:'Contains a poisonous substance, namely a mycotoxin.' },
  { code:'INADPRCCTL', section:'402(a)(4), 801(a)(3)', cat:'ADULTERATION', es:'Preparado bajo condiciones insanitarias debido a controles de proceso inadecuados', en:'Prepared under insanitary conditions due to inadequate process controls.' },
  { code:'DISEASED',   section:'402(a)(5), 801(a)(3)', cat:'ADULTERATION', es:'Producto de animal enfermo o que murio de otra forma que no fue sacrificio', en:'Product of a diseased animal or one that died other than by slaughter.' },
  { code:'GDUFA FEE',  section:'502(aa), 801(a)(3)',   cat:'MISBRANDING',  es:'Medicamento fabricado en instalacion que no ha pagado las tarifas requeridas GDUFA', en:'Drug manufactured in a facility for which fees have not been paid.' },
  { code:'CONTAMCAN',  section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contenido en recipiente con sustancia venenosa que puede hacerlo perjudicial', en:'Held in a container containing a poisonous or deleterious substance.' },
  { code:'FALSEDRUG',  section:'502(a)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Medicamento cuyo rotulado es falso o enganoso segun la seccion 502(a)(1)', en:'Drug misbranded in that its labeling is false or misleading.' },
  { code:'NO PMA',     section:'501(f)(1)(B), 801(a)(3)', cat:'ADULTERATION', es:'Dispositivo Clase III sin solicitud aprobada de aprobacion previa a comercializacion', en:'Class III device without an approved premarket approval application.' },
  { code:'BIO TOXIN',  section:'402(a)(1), 801(a)(3)', cat:'ADULTERATION', es:'Contiene sustancia venenosa y deleterea que ordinariamente lo haria perjudicial', en:'Contains a poisonous and deleterious substance which would ordinarily render it injurious.' },
  { code:'SULFITELBL', section:'403(a)(1), 801(a)(3)', cat:'MISBRANDING',  es:'Contiene sulfitos no declarados — fabricado sin listar todos los ingredientes', en:'Contains sulfites but label fails to declare them.' },
  { code:'PRESRV LBL', section:'403(k), 801(a)(3)',    cat:'MISBRANDING',  es:'Contiene conservador quimico y no tiene etiquetado que declare ese hecho', en:'Contains a chemical preservative and fails to bear labeling stating that fact.' },
];

var DEMO_SUMMARY = {
  total: 117,
  cats: [['Human Foods',78],['Drugs and Biologics',18],['Cosmetics',12],['Devices',5],['Tobacco',4]],
  years: [['2022',28],['2023',34],['2024',45],['2025',10]],
  charges: [['INSANITARY',34],['PESTICIDE',26],['NO ENGLISH',20],['LIST INGRE',17],['NUTRIT LBL',12],['AFLATOXIN',9],['LISTERIA',8],['UNAPPROVED',7]],
};
